name: Docker build and push to Docker Hub

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - id: git_checkout
        name: Git Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: version
        name: Git Version
        uses: arago/semver-release-action@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: image_build
        name: Build Docker Image
        uses: abhishek-070/docker-image-build-push-action@v1.0
        with:
          registry_url: "docker.io"
          repository_name: "laravel-example"
          user_name: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_version: ${{ steps.version.outputs.version }}
          docker_file: "./docker/8.1"
      - id: pull_url
        name: Get Pull URL
        run: echo "The url is ${{ steps.image_build.outputs.image_pull_url }}"
