name: Docker build and push to Docker Hub

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: arago/semver-release-action@v1
        with:
          bump: minor
          prefix: v
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: './socker/8.1'
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/laravel-example:v${{ steps.version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/laravel-example:latest
      - name: Metadata
        run: echo "The result is:"; echo "${{ steps.build_push.outputs.metadata }}"
