name: Docker build and push to Docker Hub

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: rickstaa/action-get-semver@v1
        with:
          bump_level: minor
          verbose: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: "./socker/8.1"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-example:${{ steps.version.outputs.current_version }},${{ secrets.DOCKERHUB_USERNAME }}/laravel-example:latest
      - name: Metadata
        run: |
          echo "The result is:"; echo "${{ steps.build_push.outputs.metadata }}"
          echo "The next major version is ${{ steps.version.outputs.next_version }}"
